In [ ]:
import numpy as np

# Data Loading and Preparation

In [ ]:
from sklearn.datasets import fetch_openml
iris = fetch_openml(name='iris', version=1)

In [ ]:
print(iris.data.shape)
print(iris.target.shape)
print(np.unique(iris.target))
print(iris.DESCR)

(150, 4)
(150,)
['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']
**Author**: R.A. Fisher  
**Source**: [UCI](https://archive.ics.uci.edu/ml/datasets/Iris) - 1936 - Donated by Michael Marshall  
**Please cite**:   

**Iris Plants Database**  
This is perhaps the best known database to be found in the pattern recognition literature.  Fisher's paper is a classic in the field and is referenced frequently to this day.  (See Duda & Hart, for example.)  The data set contains 3 classes of 50 instances each, where each class refers to a type of iris plant.  One class is     linearly separable from the other 2; the latter are NOT linearly separable from each other.

Predicted attribute: class of iris plant.  
This is an exceedingly simple domain.  
 
### Attribute Information:
    1. sepal length in cm
    2. sepal width in cm
    3. petal length in cm
    4. petal width in cm
    5. class: 
       -- Iris Setosa
       -- Iris Versicolour
       -- Iris Virginica

Downloaded from openml.org.


In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target,
                                       test_size=0.20,
                                       random_state=32,
                                       shuffle=True)

In [ ]:
print(np.shape(X_train))
print(np.shape(X_test))
print(np.shape(y_train))
print(np.shape(y_test))

(120, 4)
(30, 4)
(120,)
(30,)


# k-NN Classifier

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=7)
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=7)

In [ ]:
predicted = knn.predict(X_test)
print(predicted)

['Iris-versicolor' 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor'
 'Iris-virginica' 'Iris-virginica' 'Iris-setosa' 'Iris-setosa'
 'Iris-versicolor' 'Iris-setosa' 'Iris-versicolor' 'Iris-virginica'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-virginica' 'Iris-virginica'
 'Iris-versicolor' 'Iris-virginica' 'Iris-versicolor' 'Iris-setosa'
 'Iris-setosa' 'Iris-virginica' 'Iris-versicolor' 'Iris-setosa'
 'Iris-setosa' 'Iris-versicolor' 'Iris-setosa' 'Iris-virginica'
 'Iris-setosa' 'Iris-setosa']


## Evaluating Accuracy, Precision, Recall and F-measure of a model

In [ ]:
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay, classification_report

In [ ]:
cm = confusion_matrix(y_test, predicted)
cm

array([[12,  0,  0],
       [ 0,  9,  0],
       [ 0,  1,  8]])

In [ ]:
print(classification_report(y_test, predicted))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        12
Iris-versicolor       0.90      1.00      0.95         9
 Iris-virginica       1.00      0.89      0.94         9

       accuracy                           0.97        30
      macro avg       0.97      0.96      0.96        30
   weighted avg       0.97      0.97      0.97        30



## defining KNN from scratch

In [ ]:
from collections import Counter
k = 7
def predict(x):
    # Compute Euclidean distances between x and all examples in the training set
    distances = [np.linalg.norm(x - x_train) for x_train in X_train.values]

    # Sort by distance and return indices of the first k neighbors
    k_indices = np.argsort(distances)[:k]

    # Extract the labels of the k nearest neighbor training samples
    k_nearest_labels = [np.array(y_train)[i] for i in k_indices]
    #print(k_nearest_labels)
    # Return the most common class label
    most_common = Counter(k_nearest_labels).most_common(1)
    return most_common[0][0]

In [ ]:
predicted = [predict(x) for x in X_test.values]
print(predicted)

['Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-virginica', 'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-setosa', 'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica', 'Iris-virginica', 'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-virginica', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa', 'Iris-setosa']


In [ ]:
cm = confusion_matrix(y_test, predicted)
print(cm)
print(classification_report(y_test, predicted))

[[12  0  0]
 [ 0  9  0]
 [ 0  1  8]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        12
Iris-versicolor       0.90      1.00      0.95         9
 Iris-virginica       1.00      0.89      0.94         9

       accuracy                           0.97        30
      macro avg       0.97      0.96      0.96        30
   weighted avg       0.97      0.97      0.97        30



## Task1: use user-defined k-NN classifier for mice and breast-cancer data

In [ ]:
mice_data = fetch_openml(name='miceprotein', version=4)
print(mice_data.data.shape)
print(mice_data.target.shape)
print(np.unique(mice_data.target))
print(mice_data.DESCR)

(1080, 77)
(1080,)
['c-CS-m' 'c-CS-s' 'c-SC-m' 'c-SC-s' 't-CS-m' 't-CS-s' 't-SC-m' 't-SC-s']
**Author**: Clara Higuera, Katheleen J. Gardiner, Krzysztof J. Cios  
**Source**: [UCI](https://archive.ics.uci.edu/ml/datasets/Mice+Protein+Expression) - 2015   
**Please cite**: Higuera C, Gardiner KJ, Cios KJ (2015) Self-Organizing Feature Maps Identify Proteins Critical to Learning in a Mouse Model of Down Syndrome. PLoS ONE 10(6): e0129126.

Expression levels of 77 proteins measured in the cerebral cortex of 8 classes of control and Down syndrome mice exposed to context fear conditioning, a task used to assess associative learning.

The data set consists of the expression levels of 77 proteins/protein modifications that produced detectable signals in the nuclear fraction of cortex. There are 38 control mice and 34 trisomic mice (Down syndrome), for a total of 72 mice. In the experiments, 15 measurements were registered of each protein per sample/mouse. Therefore, for control mice, there ar

In [ ]:
import numpy as np
import pandas as pd
from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report
from collections import Counter

# Define the k-NN prediction function
def predict_knn(X_train, y_train, X_test, k):
    # Broadcasting creates an array of shape (n_train, n_test, n_features)
    distances = np.linalg.norm(X_train[:, np.newaxis] - X_test, axis=2)

    # For each test sample, get the indices of the k nearest training samples.
    # np.argsort returns indices along the training samples axis.
    k_indices = np.argsort(distances, axis=0)[:k]

    # Retrieve the labels for the k nearest neighbors.
    k_nearest_labels = np.array([y_train[idx] for idx in k_indices])

    # For each test sample, determine the most common label among the k nearest neighbors.
    predictions = [Counter(k_nearest).most_common(1)[0][0] for k_nearest in k_nearest_labels.T]
    return predictions

##########################
# MICE PROTEIN DATASET
##########################

# Load the Mice Protein dataset
mice_data = fetch_openml(name='miceprotein', version=4)

# Convert the data and target to numpy arrays
X_mice = mice_data.data.to_numpy()
y_mice = mice_data.target.to_numpy()

# Split data into training and testing sets
X_train_mice, X_test_mice, y_train_mice, y_test_mice = train_test_split(
    X_mice, y_mice, test_size=0.2, random_state=42
)

# Define k for k-NN
k = 7


predicted_mice = predict_knn(X_train_mice, y_train_mice, X_test_mice, k)

# Evaluate the Mice Protein model
cm_mice = confusion_matrix(y_test_mice, predicted_mice)
print("Mice Protein Confusion Matrix:")
print(cm_mice)
print(classification_report(y_test_mice, predicted_mice))

##########################
# BREAST CANCER DATASET
##########################

# Load the Breast Cancer dataset
breast_cancer_data = fetch_openml(name='breast-cancer', version=1)

# Convert every column to numeric by factorizing its values.
# This will replace each column with numeric codes.
breast_cancer_data.data = breast_cancer_data.data.apply(
    lambda col: pd.factorize(col.astype(str))[0]
)

# Also factorize the target labels
breast_cancer_data.target = pd.factorize(breast_cancer_data.target.astype(str))[0]

# Convert the DataFrame to numpy arrays for consistency
X_bc = breast_cancer_data.data.to_numpy()
y_bc = breast_cancer_data.target  # already numeric

# Split data into training and testing sets
X_train_bc, X_test_bc, y_train_bc, y_test_bc = train_test_split(
    X_bc, y_bc, test_size=0.2, random_state=42
)

# Predict on the Breast Cancer dataset
predicted_bc = predict_knn(X_train_bc, y_train_bc, X_test_bc, k)

# Evaluate the Breast Cancer model
cm_bc = confusion_matrix(y_test_bc, predicted_bc)
print("\nBreast Cancer Confusion Matrix:")
print(cm_bc)
print(classification_report(y_test_bc, predicted_bc))


Mice Protein Confusion Matrix:
[[ 9  0  0  0 23  0  0  0]
 [ 0 11  0  0 13  2  0  0]
 [ 0  0  7  0 20  0  0  0]
 [ 0  0  0 22 12  0  0  0]
 [ 0  0  0  0 19  0  0  0]
 [ 0  0  0  0  8 14  0  0]
 [ 0  0  0  0 11  0 14  0]
 [ 0  0  0  0 13  0  0 18]]
              precision    recall  f1-score   support

      c-CS-m       1.00      0.28      0.44        32
      c-CS-s       1.00      0.42      0.59        26
      c-SC-m       1.00      0.26      0.41        27
      c-SC-s       1.00      0.65      0.79        34
      t-CS-m       0.16      1.00      0.28        19
      t-CS-s       0.88      0.64      0.74        22
      t-SC-m       1.00      0.56      0.72        25
      t-SC-s       1.00      0.58      0.73        31

    accuracy                           0.53       216
   macro avg       0.88      0.55      0.59       216
weighted avg       0.91      0.53      0.60       216


Breast Cancer Confusion Matrix:
[[ 4 14]
 [ 3 37]]
              precision    recall  f1-score   sup

In [ ]:
cancer_data = fetch_openml(name='breast-cancer', version=1)
print(cancer_data.data.shape)
print(cancer_data.target.shape)
print(np.unique(cancer_data.target))
print(cancer_data.DESCR)

(286, 9)
(286,)
['no-recurrence-events' 'recurrence-events']
**Author**:   
**Source**: Unknown -   
**Please cite**:   

Citation Request:
    This breast cancer domain was obtained from the University Medical Centre,
    Institute of Oncology, Ljubljana, Yugoslavia.  Thanks go to M. Zwitter and 
    M. Soklic for providing the data.  Please include this citation if you plan
    to use this database.
 
 1. Title: Breast cancer data (Michalski has used this)
 
 2. Sources: 
    -- Matjaz Zwitter & Milan Soklic (physicians)
       Institute of Oncology 
       University Medical Center
       Ljubljana, Yugoslavia
    -- Donors: Ming Tan and Jeff Schlimmer (Jeffrey.Schlimmer@a.gp.cs.cmu.edu)
    -- Date: 11 July 1988
 
 3. Past Usage: (Several: here are some)
      -- Michalski,R.S., Mozetic,I., Hong,J., & Lavrac,N. (1986). The 
         Multi-Purpose Incremental Learning System AQ15 and its Testing 
         Application to Three Medical Domains.  In Proceedings of the 
         Fifth N

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(cancer_data.data, cancer_data.target,
                                       test_size=0.20,
                                       random_state=32,
                                       shuffle=True)

In [ ]:
print(X_train.iloc[0:12, :])

       age menopause tumor-size inv-nodes node-caps deg-malig breast  \
33   50-59      ge40      20-24       0-2        no         3  right   
283  30-39   premeno      30-34       6-8       yes         2  right   
46   60-69      ge40      10-14       0-2        no         2  right   
135  30-39   premeno      15-19       0-2        no         1  right   
116  40-49   premeno      30-34       6-8       yes         3  right   
235  60-69      ge40      40-44       0-2        no         2  right   
5    50-59   premeno      25-29       3-5        no         2  right   
255  50-59   premeno      25-29       0-2        no         3  right   
216  60-69      ge40      25-29       0-2        no         3   left   
200  30-39   premeno        5-9       0-2        no         2   left   
132  40-49   premeno      30-34       0-2        no         3  right   
180  30-39   premeno      40-44       0-2        no         2  right   

    breast-quad irradiat  
33      left_up       no  
283    ri

In [ ]:
print(y_train.iloc[0:12])

33     no-recurrence-events
283    no-recurrence-events
46     no-recurrence-events
135       recurrence-events
116       recurrence-events
235       recurrence-events
5      no-recurrence-events
255       recurrence-events
216       recurrence-events
200    no-recurrence-events
132       recurrence-events
180    no-recurrence-events
Name: Class, dtype: category
Categories (2, object): ['no-recurrence-events', 'recurrence-events']


## Task2: use user-defined k-NN for Regression

In [ ]:
from sklearn.datasets import fetch_california_housing
#here is the link to find all the datasets available in sklearn https://scikit-learn.org/stable/datasets.html
X, y = fetch_california_housing(return_X_y=True)

In [ ]:

import numpy as np
k = 7
def predict_regression(x):

    distances = [np.linalg.norm(x - x_train) for x_train in X_train]

    k_indices = np.argsort(distances)[:k]

    k_nearest_labels = [y_train[i] for i in k_indices]

    return np.mean(k_nearest_labels)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

predicted = [predict_regression(x) for x in X_test]
print(predicted)

from sklearn.metrics import mean_squared_error, r2_score
mse = mean_squared_error(y_test, predicted)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, predicted)

print(f"Mean Squared Error (MSE): {mse}")
print(f"Root Mean Squared Error (RMSE): {rmse}")
print(f"R-squared (R2): {r2}")


[1.7973333333333332, 1.2523333333333333, 2.8223333333333334, 2.429, 1.4929999999999997, 2.8023333333333333, 2.8256666666666668, 1.9453333333333334, 1.957666666666667, 2.842333333333334, 1.178, 1.0606666666666666, 1.6499999999999997, 2.6253333333333333, 2.1010000000000004, 2.5406666666666666, 2.4723333333333333, 1.3266666666666667, 2.9963333333333337, 1.5893333333333333, 1.18, 3.195, 1.2923333333333333, 1.5143333333333338, 1.5326666666666666, 1.147, 2.877666666666667, 1.8733333333333333, 1.5476666666666665, 2.0993333333333335, 0.7283333333333334, 1.0730000000000002, 3.048666666666667, 2.9806666666666666, 2.7176666666666667, 1.6193333333333335, 3.0303333333333335, 1.579, 1.6340000000000001, 3.3316700000000004, 2.091666666666667, 2.9006666666666665, 1.825, 2.3683333333333336, 2.467, 3.369336666666667, 2.2706666666666666, 2.037, 2.749, 2.016, 1.4253333333333333, 2.0936666666666666, 1.8066666666666666, 2.7439999999999998, 1.1206666666666667, 2.623666666666667, 1.3533333333333333, 1.64866666